void ltm_read();
void ltm_check();

#define LIGHTTELEMETRY_START1 0x24 //$
#define LIGHTTELEMETRY_START2 0x54 //T
#define LIGHTTELEMETRY_GFRAME 0x47 //G for GPS + Baro altitude data
#define LIGHTTELEMETRY_GFRAMELENGTH 19

#define	LIGHTTELEMETRY_LAT				0
#define	LIGHTTELEMETRY_LON				4
#define	LIGHTTELEMETRY_GROUNDSPEED		8
#define	LIGHTTELEMETRY_ALTITUDE			10
#define	LIGHTTELEMETRY_SATSFIX			14
	


